add few code

diff --git a/Jenkinsfile-jfrog-maven-tomcat b/Jenkinsfile-jfrog-maven-tomcat
--- a/Jenkinsfile-jfrog-maven-tomcat
+++ b/Jenkinsfile-jfrog-maven-tomcat
@@ -58,7 +58,20 @@ stages{
             }
         }
 
-     stage('Deploy to Tomcat') {
+//        stage('Deploy to Tomcat') {
+//     when {
+//         expression { params.ACTION == 'deploy' }
+//     }
+//     steps {
+//         echo "Deploying ${params.APP_NAME} to ${params.DEPLOY_ENV} environment"
+//         sh """
+//         curl -v -u admin:Anant@123 -T my_maven/target/${params.APP_NAME}.war \\
+//           "http://localhost:8080/manager/text/deploy?path=/${params.APP_NAME}&update=true"
+//         """
+//     }
+// }
+
+ stage('Deploy to Tomcat') {
     when {
         expression { params.ACTION == 'deploy' }
     }
@@ -67,13 +80,13 @@ stages{
         echo "APP_NAME: ${params.APP_NAME}"
         echo "DEPLOY_ENV: ${params.DEPLOY_ENV}"
         echo "Deploying ${params.APP_NAME} to ${params.DEPLOY_ENV} environment"
+          sh "ls -lh ${warFile} || (echo 'WAR file not found!' && exit 1)"
         sh """
-        curl -v -u admin:Anant@123 -T my_maven/target/${params.APP_NAME}.jar \\
+        curl -v -u admin:Anant@123 -T my_maven/target/${params.APP_NAME}.war \\
           "http://localhost:8080/manager/text/deploy?path=/${params.APP_NAME}&update=true"
         """
     }
 }
-
 
     }
 }
